steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'
    id: 'build-image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
    id: 'push-image'
    waitFor: ['build-image']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '${_MEMORY:-512Mi}'
      - '--cpu'
      - '${_CPU:-1}'
      - '--min-instances'
      - '${_MIN_INSTANCES:-0}'
      - '--max-instances'
      - '${_MAX_INSTANCES:-10}'
      - '--timeout'
      - '${_TIMEOUT:-300}'
      - '--set-env-vars'
      - 'ENVIRONMENT=prod,MCP_AUTH_ENABLED=${_MCP_AUTH_ENABLED:-true},MCP_AUTH_TOKEN=${_MCP_AUTH_TOKEN}'
    id: 'deploy-cloud-run'
    waitFor: ['push-image']

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _SERVICE_NAME: 'omniagentpay-mcp-server'
  _REGION: 'us-central1'
  _MEMORY: '512Mi'
  _CPU: '1'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _TIMEOUT: '300'
  _MCP_AUTH_ENABLED: 'true'
  _MCP_AUTH_TOKEN: '9507b8047086f29f78dcdf3b188f52fedb2dfd831053c723901d328e00537277'