#!/bin/bash
# FastMCP Server Test Commands (with Authentication)
# Replace YOUR_TOKEN with your actual bearer token

TOKEN="YOUR_TOKEN"
BASE_URL="http://localhost:8000"
MCP_PATH="/mcp/"

echo "=== FastMCP Server Test Commands ==="
echo "Make sure to replace YOUR_TOKEN with your actual token"
echo ""

# 1. List all available tools
echo "1. List Tools:"
echo "curl -X POST ${BASE_URL}${MCP_PATH} \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer ${TOKEN}' \\"
echo "  -d '{\"jsonrpc\": \"2.0\", \"method\": \"tools/list\", \"id\": 1}'"
echo ""

# 2. Create Agent Wallet
echo "2. Create Agent Wallet:"
echo "curl -X POST ${BASE_URL}${MCP_PATH} \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer ${TOKEN}' \\"
echo "  -d '{"
echo "    \"jsonrpc\": \"2.0\","
echo "    \"method\": \"tools/call\","
echo "    \"params\": {"
echo "      \"name\": \"create_agent_wallet\","
echo "      \"arguments\": {"
echo "        \"agent_name\": \"test_agent\""
echo "      }"
echo "    },"
echo "    \"id\": 2"
echo "  }'"
echo ""

# 3. Check Balance
echo "3. Check Balance:"
echo "curl -X POST ${BASE_URL}${MCP_PATH} \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer ${TOKEN}' \\"
echo "  -d '{"
echo "    \"jsonrpc\": \"2.0\","
echo "    \"method\": \"tools/call\","
echo "    \"params\": {"
echo "      \"name\": \"check_balance\","
echo "      \"arguments\": {"
echo "        \"wallet_id\": \"your_wallet_id_here\""
echo "      }"
echo "    },"
echo "    \"id\": 3"
echo "  }'"
echo ""

# 4. Simulate Payment
echo "4. Simulate Payment:"
echo "curl -X POST ${BASE_URL}${MCP_PATH} \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer ${TOKEN}' \\"
echo "  -d '{"
echo "    \"jsonrpc\": \"2.0\","
echo "    \"method\": \"tools/call\","
echo "    \"params\": {"
echo "      \"name\": \"simulate_payment\","
echo "      \"arguments\": {"
echo "        \"from_wallet_id\": \"wallet_123\","
echo "        \"to_address\": \"0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb\","
echo "        \"amount\": \"10.50\","
echo "        \"currency\": \"USD\""
echo "      }"
echo "    },"
echo "    \"id\": 4"
echo "  }'"
echo ""

# 5. Pay Recipient
echo "5. Pay Recipient:"
echo "curl -X POST ${BASE_URL}${MCP_PATH} \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer ${TOKEN}' \\"
echo "  -d '{"
echo "    \"jsonrpc\": \"2.0\","
echo "    \"method\": \"tools/call\","
echo "    \"params\": {"
echo "      \"name\": \"pay_recipient\","
echo "      \"arguments\": {"
echo "        \"from_wallet_id\": \"wallet_123\","
echo "        \"to_address\": \"0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb\","
echo "        \"amount\": \"10.50\","
echo "        \"currency\": \"USD\""
echo "      }"
echo "    },"
echo "    \"id\": 5"
echo "  }'"
echo ""

# 6. Create Payment Intent
echo "6. Create Payment Intent:"
echo "curl -X POST ${BASE_URL}${MCP_PATH} \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer ${TOKEN}' \\"
echo "  -d '{"
echo "    \"jsonrpc\": \"2.0\","
echo "    \"method\": \"tools/call\","
echo "    \"params\": {"
echo "      \"name\": \"create_payment_intent\","
echo "      \"arguments\": {"
echo "        \"wallet_id\": \"wallet_123\","
echo "        \"recipient\": \"0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb\","
echo "        \"amount\": \"10.50\","
echo "        \"currency\": \"USD\","
echo "        \"metadata\": {\"purpose\": \"test payment\"}"
echo "      }"
echo "    },"
echo "    \"id\": 6"
echo "  }'"
echo ""

# 7. Confirm Payment Intent
echo "7. Confirm Payment Intent:"
echo "curl -X POST ${BASE_URL}${MCP_PATH} \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer ${TOKEN}' \\"
echo "  -d '{"
echo "    \"jsonrpc\": \"2.0\","
echo "    \"method\": \"tools/call\","
echo "    \"params\": {"
echo "      \"name\": \"confirm_payment_intent\","
echo "      \"arguments\": {"
echo "        \"intent_id\": \"your_intent_id_here\""
echo "      }"
echo "    },"
echo "    \"id\": 7"
echo "  }'"
echo ""

# 8. Remove Recipient Guard
echo "8. Remove Recipient Guard:"
echo "curl -X POST ${BASE_URL}${MCP_PATH} \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer ${TOKEN}' \\"
echo "  -d '{"
echo "    \"jsonrpc\": \"2.0\","
echo "    \"method\": \"tools/call\","
echo "    \"params\": {"
echo "      \"name\": \"remove_recipient_guard\","
echo "      \"arguments\": {"
echo "        \"wallet_id\": \"wallet_123\""
echo "      }"
echo "    },"
echo "    \"id\": 8"
echo "  }'"
echo ""

# 9. Add Recipient to Whitelist
echo "9. Add Recipient to Whitelist:"
echo "curl -X POST ${BASE_URL}${MCP_PATH} \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer ${TOKEN}' \\"
echo "  -d '{"
echo "    \"jsonrpc\": \"2.0\","
echo "    \"method\": \"tools/call\","
echo "    \"params\": {"
echo "      \"name\": \"add_recipient_to_whitelist\","
echo "      \"arguments\": {"
echo "        \"wallet_id\": \"wallet_123\","
echo "        \"addresses\": ["
echo "          \"0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb\","
echo "          \"0x8ba1f109551bD432803012645Hac136c22C929\""
echo "        ]"
echo "      }"
echo "    },"
echo "    \"id\": 9"
echo "  }'"
echo ""
